### ISSUE TITLE
Changing URL path segment does not reload page tree

### ISSUE THREAD

**Issue by TheLalaMan** [mocdk/MOC.SynchronizeUrl#3]
I tried your package with Neos 2.3.7. Seems to be working only one-way, though. If I change the URL instead of the title, I get a 404 in the backend and incoming links as well. After reloading the page tree, everything works. So, it seems that renaming the Page triggers a page tree reload, but changing the URL path segment does not.

**Comment by aertmann** [comment]
Hey thanks for reporting this issue, however this is an issue in Neos and not related to this package.

**Comment by TheLalaMan** [comment]
Are you sure about that? Because if I do not include your package, everything works as expected when changing the URL path segment... imho this is not a Neos bug.
